/* Wallet top-up and wallet booking-payment schema patch.
   Run after 20260722_wallet_refund_schema.sql. SQLCMD GO batches are intentional:
   SQL Server compiles CREATE INDEX statements before an ALTER TABLE in the same batch. */
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
BEGIN TRANSACTION;
GO

IF COL_LENGTH('dbo.PAYMENTS', 'idempotency_key_hash') IS NULL
    ALTER TABLE dbo.PAYMENTS ADD idempotency_key_hash NVARCHAR(128) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UQ_PAY_BOOKING_IDEMPOTENCY' AND object_id = OBJECT_ID('dbo.PAYMENTS'))
    CREATE UNIQUE INDEX UQ_PAY_BOOKING_IDEMPOTENCY ON dbo.PAYMENTS(booking_id, idempotency_key_hash) WHERE idempotency_key_hash IS NOT NULL;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UQ_PAY_BOOKING_SUCCESS' AND object_id = OBJECT_ID('dbo.PAYMENTS'))
    CREATE UNIQUE INDEX UQ_PAY_BOOKING_SUCCESS ON dbo.PAYMENTS(booking_id) WHERE status = 'SUCCESS';
GO

IF OBJECT_ID('dbo.WALLET_TOPUPS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.WALLET_TOPUPS
    (
        id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_WALLET_TOPUPS PRIMARY KEY DEFAULT (newsequentialid()),
        wallet_id UNIQUEIDENTIFIER NOT NULL,
        requested_by UNIQUEIDENTIFIER NOT NULL,
        amount DECIMAL(18,2) NOT NULL,
        status NVARCHAR(20) NOT NULL CONSTRAINT DF_WALLET_TOPUP_STATUS DEFAULT (N'PENDING'),
        gateway_txn_id NVARCHAR(100) NULL,
        response_code NVARCHAR(10) NULL,
        transaction_status NVARCHAR(10) NULL,
        idempotency_key_hash NVARCHAR(128) NOT NULL,
        created_at DATETIME2 NOT NULL CONSTRAINT DF_WALLET_TOPUP_CREATED DEFAULT (sysdatetime()),
        expires_at DATETIME2 NOT NULL,
        completed_at DATETIME2 NULL,
        row_version ROWVERSION NOT NULL,
        CONSTRAINT CK_WALLET_TOPUP_AMOUNT CHECK (amount > 0),
        CONSTRAINT CK_WALLET_TOPUP_STATUS CHECK (status IN (N'PENDING', N'SUCCESS', N'FAILED', N'EXPIRED')),
        CONSTRAINT FK_WALLET_TOPUP_WALLET FOREIGN KEY (wallet_id) REFERENCES dbo.WALLETS(id) ON DELETE CASCADE,
        CONSTRAINT FK_WALLET_TOPUP_REQUESTER FOREIGN KEY (requested_by) REFERENCES dbo.USERS(id)
    );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UQ_WALLET_TOPUP_IDEMPOTENCY' AND object_id = OBJECT_ID('dbo.WALLET_TOPUPS'))
    CREATE UNIQUE INDEX UQ_WALLET_TOPUP_IDEMPOTENCY ON dbo.WALLET_TOPUPS(requested_by, idempotency_key_hash);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UQ_WALLET_TOPUP_GATEWAY_TXN' AND object_id = OBJECT_ID('dbo.WALLET_TOPUPS'))
    CREATE UNIQUE INDEX UQ_WALLET_TOPUP_GATEWAY_TXN ON dbo.WALLET_TOPUPS(gateway_txn_id) WHERE gateway_txn_id IS NOT NULL;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_WALLET_TOPUP_STATUS_CREATED' AND object_id = OBJECT_ID('dbo.WALLET_TOPUPS'))
    CREATE INDEX IX_WALLET_TOPUP_STATUS_CREATED ON dbo.WALLET_TOPUPS(status, created_at DESC);
GO

IF COL_LENGTH('dbo.WALLET_TRANSACTIONS', 'payment_id') IS NULL
    ALTER TABLE dbo.WALLET_TRANSACTIONS ADD payment_id UNIQUEIDENTIFIER NULL;
IF COL_LENGTH('dbo.WALLET_TRANSACTIONS', 'wallet_topup_id') IS NULL
    ALTER TABLE dbo.WALLET_TRANSACTIONS ADD wallet_topup_id UNIQUEIDENTIFIER NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_WALLET_TX_PAYMENT')
    ALTER TABLE dbo.WALLET_TRANSACTIONS ADD CONSTRAINT FK_WALLET_TX_PAYMENT FOREIGN KEY (payment_id) REFERENCES dbo.PAYMENTS(id);
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_WALLET_TX_TOPUP')
    ALTER TABLE dbo.WALLET_TRANSACTIONS ADD CONSTRAINT FK_WALLET_TX_TOPUP FOREIGN KEY (wallet_topup_id) REFERENCES dbo.WALLET_TOPUPS(id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UQ_WALLET_TX_PAYMENT' AND object_id = OBJECT_ID('dbo.WALLET_TRANSACTIONS'))
    CREATE UNIQUE INDEX UQ_WALLET_TX_PAYMENT ON dbo.WALLET_TRANSACTIONS(payment_id) WHERE payment_id IS NOT NULL;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UQ_WALLET_TX_TOPUP' AND object_id = OBJECT_ID('dbo.WALLET_TRANSACTIONS'))
    CREATE UNIQUE INDEX UQ_WALLET_TX_TOPUP ON dbo.WALLET_TRANSACTIONS(wallet_topup_id) WHERE wallet_topup_id IS NOT NULL;
GO

IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE parent_object_id = OBJECT_ID('dbo.WALLET_TRANSACTIONS') AND name = 'CK_WALLET_TX_TYPE')
    ALTER TABLE dbo.WALLET_TRANSACTIONS DROP CONSTRAINT CK_WALLET_TX_TYPE;
ALTER TABLE dbo.WALLET_TRANSACTIONS ADD CONSTRAINT CK_WALLET_TX_TYPE CHECK (type IN (N'REFUND_CREDIT', N'WITHDRAWAL_HOLD', N'WITHDRAWAL_REVERSAL', N'TOPUP_CREDIT', N'BOOKING_PAYMENT_DEBIT'));
GO

COMMIT TRANSACTION;
GO

PRINT 'Wallet top-up and wallet-payment schema patch applied.';
